const TOTAL_COINS = 1000;

const TRANSACTION_THRESHOLD = 2;

const FIRST_LEADER = "";

const TRANSACTION_FEE = 1;

const MINIMUM_ROYALTY = 50;

module.exports = {
  TOTAL_COINS,
  TRANSACTION_THRESHOLD,
  FIRST_LEADER,
  TRANSACTION_FEE,
  MINIMUM_ROYALTY
};
